<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>ChompMan.Tests</RootNamespace>
    <AssemblyName>ChompMan.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="3.3.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ChompMan.Core\ChompMan.Core.csproj" />
  </ItemGroup>
</Project>
